// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'todomvc.models.Application' );
goog.provide( 'todomvc.models.ApplicationDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );

goog.require( 'todomvc.models.Item' );


/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
todomvc.models.ApplicationDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.input = undefined;

    /**
     * @type {boolean}
     */
    this.completeAll = undefined;

    /**
     * @type {todomvc.models.Item}
     */
    this.itemStorage = undefined;

    /**
     * @type {todomvc.models.Item}
     */
    this.itemView = undefined;

    /**
     * @type {number}
     */
    this.activeItemsNumber = undefined;

    /**
     * @type {number}
     */
    this.completedItemsNumber = undefined;

    /**
     * @type {boolean}
     */
    this.showAll = undefined;

    /**
     * @type {boolean}
     */
    this.showActive = undefined;

    /**
     * @type {boolean}
     */
    this.showCompleted = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( todomvc.models.ApplicationDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
todomvc.models.Application = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( todomvc.models.Application, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {todomvc.models.ApplicationDatarow}
*/
todomvc.models.Application.prototype.DatarowConstructor = todomvc.models.ApplicationDatarow;

/**
* Return todomvc.models.ApplicationDatarow schema object.
* @override
* @returns {Object}
*/
todomvc.models.Application.prototype.getDatarowSchema = function( ){

return {
        input: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        completeAll: {
                index: 1,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        itemStorage: {
                index: 2,
                type: todomvc.models.Item,
                required: false
        },
        itemView: {
                index: 3,
                type: todomvc.models.Item,
                required: false
        },
        activeItemsNumber: {
                index: 4,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        completedItemsNumber: {
                index: 5,
                type: zz.models.enums.FieldType.NUMBER,
                required: false
        },
        showAll: {
                index: 6,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        showActive: {
                index: 7,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        },
        showCompleted: {
                index: 8,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        }
};
};