// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'todomvc.models.Item' );
goog.provide( 'todomvc.models.ItemDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
todomvc.models.ItemDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.text = undefined;

    /**
     * @type {boolean}
     */
    this.completed = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( todomvc.models.ItemDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
todomvc.models.Item = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( todomvc.models.Item, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {todomvc.models.ItemDatarow}
*/
todomvc.models.Item.prototype.DatarowConstructor = todomvc.models.ItemDatarow;

/**
* Return todomvc.models.ItemDatarow schema object.
* @override
* @returns {Object}
*/
todomvc.models.Item.prototype.getDatarowSchema = function( ){

return {
        text: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        completed: {
                index: 1,
                type: zz.models.enums.FieldType.BOOLEAN,
                required: false
        }
};
};